# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'EventsInformer' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EventsInformer
  
  pod 'FBSDKCoreKit', '~> 4.14'
  pod 'FBSDKLoginKit', '~> 4.14'
  pod 'FBSDKShareKit', '~> 4.14'

  target 'EventsInformerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EventsInformerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
